//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public string photo { get; set; }
        public string Name { get; set; }
        public Nullable<int> Age { get; set; }
        public string Gender { get; set; }
        public string MobileNumber { get; set; }
        public string AltMobileNumber { get; set; }
        public string EMail { get; set; }
        public string Address { get; set; }
        public string RefreedBy { get; set; }
        public string GenralHelth { get; set; }
        public string Allergies { get; set; }
        public string ConditionFoHair { get; set; }
        public string HairLength { get; set; }
        public string Colour { get; set; }
        public Nullable<int> Density { get; set; }
        public Nullable<System.DateTime> consultaionDate { get; set; }
        public Nullable<System.DateTime> ReplacementDate { get; set; }
        public string System1 { get; set; }
        public string System2 { get; set; }
        public string System3 { get; set; }
        public string Size { get; set; }
        public string LifeSpan { get; set; }
        public decimal price { get; set; }
        public Nullable<decimal> AdvancePayment { get; set; }
        public Nullable<decimal> BalancePayment { get; set; }
        public string Dispersion { get; set; }
    }
}
