//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Enqiry
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> EQDate { get; set; }
        public Nullable<System.DateTime> AvaliDate { get; set; }
        public string Discription { get; set; }
    }
}
