//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HairClinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remaider
    {
        //public int Id { get; set; }
        public int EnqId { get; set; }
        public string name { get; set; }
        public string Phone { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Feedback { get; set; }
    }
}
